### ISSUE TITLE
Happened again, even after update.

### ISSUE THREAD

**Issue by gustavosmendes** [AnKing-VIP/anki-field-autocomplete#4]
Happened again, even after update. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2021-09-07 00:54:01

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 589, in _onBridgeCmd
  File "aqt\hooks_gen.py", line 4000, in __call__
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 26, in handle_bridge_commands
    if handle_autocomplete(cmd, editor):
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 65, in handle_autocomplete
    nids = col.find_notes(query)
  File "anki\collection.py", line 503, in find_notes
  File "anki\_backend\generated.py", line 762, in search_notes
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨an opening double quote <code>"</code> was found, but there was no second one to close it. If you want to search for a literal <code>"</code>, prepend a backslash: <code>\"</code>.⁩</p>

I tested it with all addons disabled... This time, the symbol was ' and ".  You can reproduce if you type ';" (single quote and after a double quote). 
Also, the add-on really stop working, now it's a real bug

_Originally posted by @gustavosmendes in https://github.com/ankipalace/anki-field-autocomplete/issues/3#issuecomment-914755111_

**Comment by RisingOrange** [comment]
It should work now. I made a mistake earlier and the changes I made to fix the error didn't make it to Ankiweb.

**Comment by gustavosmendes** [comment]
Found another one - just tried to type to verify if was everything ok. If you type 'single quotation, backslash, single quotation'

![image](https://user-images.githubusercontent.com/87918773/132540879-5bb2d4dc-3a31-4931-b590-b47a82bae0a0.png)


Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 589, in _onBridgeCmd
  File "aqt\hooks_gen.py", line 4000, in __call__
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 26, in handle_bridge_commands
    if handle_autocomplete(cmd, editor):
  File "C:\Users\gusta\AppData\Roaming\Anki2\addons21\511710206\webview.py", line 66, in handle_autocomplete
    nids = col.find_notes(query)
  File "anki\collection.py", line 503, in find_notes
  File "anki\_backend\generated.py", line 762, in search_notes
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨the escape sequence <code>⁨\'⁩</code> is not defined. If you want to search for a literal backslash <code>\</code>, prepend another one: <code>\\</code>.⁩</p>

Again, thank you for all your effort. I'm just doing this for trying to help you. <3

**Comment by RisingOrange** [comment]
Updated the add-on again!

**Comment by gustavosmendes** [comment]
> Updated the add-on again!

You are the best!
